services:
  app:
    build: .
    ports:
      - "4100:4100"
    environment:

      DATABASE_URL: "mongodb://root:${MONGO_PASSWORD}@mongo:27017/task-manager?authSource=admin"
      JWT_SECRET: ${JWT_SECRET}
      PORT: 4100
    depends_on:
      - mongo                
    restart: always

  mongo:
    image: bitnami/mongodb:latest
    container_name: task_db
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGODB_REPLICA_SET_MODE: primary
      MONGODB_ADVERTISED_HOSTNAME: mongo
      MONGODB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGODB_REPLICA_SET_KEY: somekey123
    volumes:
      - mongo_data:/bitnami/mongodb

volumes:
  mongo_data: